### ISSUE TITLE
Errors on libfuse

### ISSUE THREAD

**Issue by dancsant** [csanthoshS/pyfuse3#5]
pyfuse3 syntax, error

# python hell.py 
Traceback (most recent call last):
  File "hell.py", 
    main()
  File "hell.py", line 48, in main
    trio.run(pyfuse3.main)
  File "src/pyfuse3.pyx", line 67, in main
  File "src/pyfuse3.pyx", line 70, in pyfuse3.main
AttributeError: 'NoneType' object has no attribute 'start_soon'

Tools to use;
pyfuse3==3.1.1
readline==6.2.4.1
sniffio==1.2.0
sortedcontainers==2.3.0
trio==0.17.0

**Comment by Rprabudeva** [comment]
I would like to contribute

**Comment by Rprabudeva** [comment]
I would like to contribute this one

**Comment by dancsant** [comment]
Proceed your work.

**Comment by Rprabudeva** [comment]
![IMG-20201206-WA0007](https://user-images.githubusercontent.com/73109985/101272950-022d5400-37b7-11eb-943b-2fefb9cd6cee.jpg)

**Comment by Rprabudeva** [comment]
I gone through this issue and find some errors in it. 
![IMG-20201206-WA0007](https://user-images.githubusercontent.com/73109985/101272987-415ba500-37b7-11eb-8167-d0de3d6e6ce5.jpg)

**Comment by Rprabudeva** [comment]
Error: pyfuse3. We should use _pyfuse3 instead of pyfuse3.
Error: stat as error. We should use _stat instead of stat.
Error: trio. We should define trio source file in src folder.

To add trio source file, use this link to download: https://github.com/python-trio/trio

**Comment by dancsant** [comment]
I check and continue with it.
